const TRIP = {
  city: "Copenaghen",
  datesLabel: "9–13 ottobre 2026",
  tagline: "Cinque giorni a piedi tra canali, palazzi, shopping e dove mangiare",
  hotel: {
    name: "Wakeup Copenhagen — Borgergade",
    address: "Borgergade 9, 1300 København K",
    lat: 55.6835,
    lng: 12.5867,
    note: "Indre By, a 5 minuti a piedi da Kongens Nytorv e Nyhavn. Rosenborg è a 7 minuti.",
  },
  flights: [
    {
      when: "Venerdì 9 ottobre",
      direction: "Andata",
      from: "Milano Linate (LIN)",
      to: "Copenaghen (CPH)",
      depart: "17:55",
      arrive: "20:05",
      airline: "easyJet",
    },
    {
      when: "Martedì 13 ottobre",
      direction: "Ritorno",
      from: "Copenaghen (CPH)",
      to: "Milano Linate (LIN)",
      depart: "20:30",
      arrive: "22:35",
      airline: "easyJet",
    },
  ],
  practical: [
    {
      title: "Hotel",
      text: "Wakeup Borgergade è il punto migliore da cui partire: il centro storico, Nyhavn e i palazzi reali si fanno quasi tutti a piedi.",
    },
    {
      title: "Metro aeroporto",
      text: "Dall’arrivi del Terminal 3 prendi la M2 direzione Vanløse e scendi a Kongens Nytorv (14 minuti, 24/7). Poi 5 minuti a piedi in Borgergade. Biglietto 3 zone: 30 DKK (~4 €), app Rejsebillet o macchinetta.",
    },
    {
      title: "Come muoversi",
      text: "In questi giorni si cammina. Il City Pass Small (zone 1–4, aeroporto incluso) serve solo se usate spesso metro e harbour bus: 96 ore 280 DKK (~37 €), 120 ore 340 DKK (~45 €). Altrimenti due biglietti aeroporto (60 DKK, ~8 €) bastano.",
    },
    {
      title: "Ottobre",
      text: "8–13 °C, possibile pioggia, tramonto verso le 18:20. Giacca, scarpe comode, un layer in più per Tivoli di sera.",
    },
    {
      title: "Mangiare",
      text: "Tre tappe fisse: Gasoline Grill il sabato per l’hamburger, Poulette il lunedì per il panino al pollo, Delphine la domenica per la cena elegante. Il resto ruota intorno.",
    },
    {
      title: "Aarhus",
      text: "Domenica si va ad ARoS in treno (DSB InterCityLyn, circa 2h 50min da København H). Il lunedì il museo è chiuso: è l’unico giorno possibile. Prenotate i treni Orange su dsb.dk e lo slot per The Dome su aros.dk.",
    },
    {
      title: "Shopping",
      text: "Sabato il cluster vicino all’hotel: WILDE, Anonymous, Naked, poi Collector’s Cage su Amagertorv. Lunedì Samsøe Samsøe e Carmen nel quartiere latino, accanto alla biblioteca e alla Torre Rotonda.",
    },
  ],
  days: [
    {
      id: 1,
      date: "9 ottobre",
      year: "2026",
      weekday: "Venerdì",
      shortDate: "09",
      title: "Arrivo e prima sera a Nyhavn",
      neighborhoods: ["Aeroporto", "Indre By", "Nyhavn"],
      summary:
        "Si atterra dopo le otto. Metro, check-in, Nyhavn, e cena da Café Oscar a due minuti: è aperto fino alle 22:00.",
      image: "img/nyhavn.jpg",
      imageCredit: "Nyhavn",
      pace: "Sera leggera",
      stops: [
        {
          time: "17:55",
          title: "Decollo da Milano Linate",
          image: "img/linate.jpg",
          place: "Aeroporto di Milano Linate",
          neighborhood: "Milano",
          type: "volo",
          description:
            "Volo easyJet LIN → CPH. Arrivo previsto alle 20:05. Tenete a portata il telefono per scaricare il biglietto metro all’arrivo (app Rejsebillet).",
          hours: "Imbarco secondo easyJet",
          tickets: "Volo già prenotato",
          how: "In aeroporto a Linate con il margine che usate di solito per easyJet.",
          duration: "2h 10min",
          lat: 45.4451,
          lng: 9.2767,
          maps: "Milan Linate Airport",
        },
        {
          time: "20:05",
          title: "Arrivo a Copenaghen e metro in centro",
          image: "img/cph-airport.jpg",
          place: "Copenhagen Airport — stazione Lufthavnen",
          neighborhood: "Kastrup",
          type: "trasporto",
          description:
            "Seguite i cartelli Metro in fondo al Terminal 3. Prendete la linea M2 verso Vanløse, senza cambi, fino a Kongens Nytorv. I treni passano ogni pochi minuti anche di sera.",
          hours: "Metro 24 ore su 24",
          tickets: "30 DKK a persona (~4 €), 3 zone. Valido 90 minuti.",
          how: "Macchinetta in stazione o app Rejsebillet prima di salire. Direzione Vanløse, 8 fermate, circa 14 minuti.",
          duration: "25–35 min fino all’hotel",
          lat: 55.618,
          lng: 12.6508,
          maps: "Copenhagen Airport Metro Lufthavnen",
        },
        {
          time: "21:00",
          title: "Check-in all’hotel",
          image: "img/kongens-nytorv.jpg",
          place: "Wakeup Copenhagen Borgergade",
          neighborhood: "Indre By",
          type: "hotel",
          description:
            "Da Kongens Nytorv uscite verso Gothersgade / Adelgade e in 5 minuti siete in Borgergade 9. L’hotel è semplice, centralissimo, e da qui parte tutto il viaggio.",
          hours: "Reception 24h",
          tickets: "Soggiorno già prenotato",
          how: "5 minuti a piedi dalla metro. Non serve taxi.",
          duration: "check-in",
          lat: 55.6835,
          lng: 12.5867,
          maps: "Wakeup Copenhagen Borgergade, Borgergade 9",
        },
        {
          time: "21:20",
          title: "Passeggiata serale a Nyhavn",
          image: "img/nyhavn.jpg",
          place: "Nyhavn",
          neighborhood: "Nyhavn",
          type: "passeggiata",
          description:
            "Il porto interno più fotografato della città è a 6 minuti dall’hotel. Case colorate, alberi dei velieri, luci sull’acqua. Un giro breve, poi cena: Oscar è a otto minuti.",
          hours: "Spazio pubblico, sempre aperto",
          tickets: "Gratis",
          how: "A piedi da Borgergade verso Kongens Nytorv, poi dritti sul canale.",
          duration: "20 min",
          lat: 55.6799,
          lng: 12.5906,
          maps: "Nyhavn, Copenhagen",
        },
        {
          time: "21:50",
          title: "Cena da Café Oscar",
          image: "img/bredgade.jpg",
          place: "Café Oscar",
          neighborhood: "Frederiksstaden",
          type: "cena",
          description:
            "Bredgade 58, tra l’hotel e la Marmorkirken. Cucina danese, smørrebrød, aperto fino alle 22:00: è il posto giusto la sera dell’arrivo, senza prenotazione da farneticare. Domani ci ripassate di giorno per il giro reale.",
          hours: "Tutti i giorni 9:30–22:00",
          tickets: "Cena circa 250–400 DKK (~33–53 €) a testa. Non serve prenotare se arrivate verso le 22:00, ma a ottobre può essere pieno: se potete, un messaggio nel pomeriggio.",
          how: "8 minuti a piedi da Nyhavn, 6 dall’hotel, lungo Bredgade.",
          duration: "45–60 min",
          lat: 55.6847,
          lng: 12.5896,
          maps: "Cafe Oscar, Bredgade 58, Copenhagen",
        },
      ],
    },
    {
      id: 2,
      date: "10 ottobre",
      year: "2026",
      weekday: "Sabato",
      shortDate: "10",
      title: "Reali, Gasoline e Broens di sera",
      neighborhoods: ["Nyboder", "Frederiksstaden", "Strøget", "Slotsholmen", "Christianshavn"],
      summary:
        "Nyboder, Marmorkirken, Kastellet. Pranzo obbligatorio da Gasoline Grill. Shopping su Strøget, Diamante Nero, poi Broens Street Food di sera con una Fritz-Cola.",
      image: "img/amalienborg.jpg",
      imageCredit: "Amalienborg e Marmorkirken",
      pace: "Giornata intera · a piedi",
      stops: [
        {
          time: "08:15",
          title: "Colazione da Hart Bageri",
          image: "img/kongens-nytorv.jpg",
          place: "Hart Bageri — Store Kongensgade 75",
          neighborhood: "Frederiksstaden",
          type: "colazione",
          description:
            "Il forno dell’ex pastry chef di Noma, a 5 minuti dall’hotel. Pane di lievito madre, croissant, cardamomo. Arrivate all’apertura: il pane buono finisce. C’è anche una Hart in Gammel Mønt, più in centro, se questa ha coda.",
          hours: "Di solito 7:30–18:00",
          tickets: "Colazione 60–120 DKK (~8–16 €). Solo da asporto o pochi sgabelli: si mangia in piedi o al volo.",
          how: "Da Borgergade a destra su Store Kongensgade, 5 minuti.",
          duration: "30 min",
          lat: 55.6852,
          lng: 12.5883,
          maps: "Hart Bageri, Store Kongensgade 75, Copenhagen",
        },
        {
          time: "08:50",
          title: "Nyboder",
          image: "img/nyboder.jpg",
          place: "Nyboder",
          neighborhood: "Nyboder",
          type: "passeggiata",
          description:
            "Le file gialle volute da Cristiano IV per i marinai. Siete già lì: Borgergade taglia il quartiere. Sankt Pauls Gade è la più fotografata. Dieci minuti lenti, poi si scende verso Marmorkirken.",
          hours: "Quartiere abitato, sempre percorribile. Nyboder Mindestuer (museo) solo domenica 11:00–14:00, oggi è chiuso.",
          tickets: "Passeggiata gratis",
          how: "Da Hart, 3 minuti verso Sankt Pauls Gade / Suensonsgade.",
          duration: "20 min",
          lat: 55.6872,
          lng: 12.5893,
          maps: "Sankt Pauls Gade, Nyboder, Copenhagen",
        },
        {
          time: "09:30",
          title: "Nyhavn di giorno",
          image: "img/nyhavn.jpg",
          place: "Nyhavn",
          neighborhood: "Nyhavn",
          type: "passeggiata",
          description:
            "Al mattino il canale è più vuoto e la luce è migliore. Camminate entrambi i lati: il lato nord (numeri dispari) è quello delle facciate più famose.",
          hours: "Sempre aperto",
          tickets: "Gratis",
          how: "10 minuti da Nyboder verso Kongens Nytorv e il canale.",
          duration: "30 min",
          lat: 55.6799,
          lng: 12.5906,
          maps: "Nyhavn, Copenhagen",
        },
        {
          time: "10:15",
          title: "Lungomare verso il Teatro Reale",
          image: "img/playhouse.jpg",
          place: "Skuespilhuset e Inderhavnsbroen",
          neighborhood: "Frederiksstaden",
          type: "passeggiata",
          description:
            "Dal fondo di Nyhavn seguite l’acqua verso il Playhouse. Di fronte, sull’acqua, c’è l’Opera.",
          hours: "Esterni sempre aperti",
          tickets: "Gratis",
          how: "A piedi lungo il porto, 8 minuti da Nyhavn.",
          duration: "15 min",
          lat: 55.6794,
          lng: 12.5955,
          maps: "Royal Danish Playhouse, Copenhagen",
        },
        {
          time: "10:45",
          title: "Frederiks Kirke (Marmorkirken)",
          image: "img/marmorkirken.jpg",
          place: "Frederiks Kirke — Marmorkirken",
          neighborhood: "Frederiksstaden",
          type: "visita",
          description:
            "La chiesa di Federico, quella di marmo con la cupola verde. Vale la facciata e la piazza, anche senza salire.",
          hours: "Di solito 10:00–17:00",
          tickets: "Chiesa gratis. Cupola a pagamento se volete salirci.",
          how: "Da Nyhavn / Bredgade, 8 minuti. Poi siete già ad Amalienborg.",
          duration: "20 min",
          lat: 55.6851,
          lng: 12.5894,
          maps: "Marmorkirken, Copenhagen",
        },
        {
          time: "11:30",
          title: "Amalienborg e cambio della guardia",
          image: "img/amalienborg.jpg",
          place: "Amalienborg Slotsplads",
          neighborhood: "Frederiksstaden",
          type: "visita",
          description:
            "Ogni giorno alle 12:00 il cambio della guardia in piazza, gratis. Arrivate entro le 11:45. La Guardia parte dalla caserma di Gothersgade verso le 11:27.",
          hours: "Piazza sempre aperta. Cambio alle 12:00",
          tickets: "Piazza e cerimonia gratis. Museo 125 DKK (~17 €) online se volete entrare.",
          how: "2 minuti a piedi dalla Marmorkirken.",
          duration: "40 min",
          lat: 55.684,
          lng: 12.5929,
          maps: "Amalienborg, Copenhagen",
        },
        {
          time: "12:20",
          title: "Kastellet e la Sirenetta",
          image: "img/kastellet.jpg",
          place: "Kastellet e Den Lille Havfrue",
          neighborhood: "Østerbro",
          type: "passeggiata",
          description:
            "Cittadella a stella, fossati, mulino. Cinque minuti più in là la Sirenetta: piccola, si fotografa, si riparte. All’uscita, su Esplanaden 14, c’è Buka Bakery se volete un caffè prima del burger: non è un pasto, è il forno sotto casa (l’altra sede è Store Kongensgade 18).",
          hours: "Kastellet circa 6:00–22:00. Sirenetta sempre visibile",
          tickets: "Gratis",
          how: "10 minuti da Amalienborg verso nord, poi 5 minuti ai bastioni.",
          duration: "50 min",
          lat: 55.692,
          lng: 12.5938,
          maps: "Kastellet, Copenhagen",
        },
        {
          time: "13:20",
          title: "Pranzo da Gasoline Grill — ci dovete andare",
          image: "img/stroget.jpg",
          place: "Gasoline Grill — Købmagergade 23",
          neighborhood: "Indre By",
          type: "pranzo",
          description:
            "Tappa fissa, non opzionale. I burger più famosi della città, carne danese, fino a esaurimento. Questa è LA volta: lunedì fate il food market, martedì Jagger. Arrivate prima delle 14:00. App Gasoline Grill per preordinare se la coda è lunga.",
          hours: "Burger tutti i giorni dalle 11:00 fino a esaurimento",
          tickets: "Burger circa 90–130 DKK (~12–17 €). Non si prenota. App Gasoline Grill per preordine.",
          how: "25 minuti a piedi dalla Sirenetta via Bredgade / Kongens Nytorv, oppure 15 da Amalienborg se saltate la Sirenetta.",
          duration: "45 min",
          lat: 55.6796,
          lng: 12.5775,
          maps: "Gasoline Grill, Købmagergade 23, Copenhagen",
        },
        {
          time: "14:30",
          title: "Shopping: WILDE, Naked, Anonymous",
          image: "img/kongens-nytorv.jpg",
          place: "Store Kongensgade, Regnegade, Grønnegade",
          neighborhood: "Indre By",
          type: "shopping",
          description:
            "Tre negozi a due minuti l’uno dall’altro, tutti aperti il sabato e a 5 minuti dall’hotel. WILDE (Store Kongensgade 22): vintage di designer. Naked (Regnegade 2): sneakers. Anonymous (Grønnegade 27): occhiali danesi. Accanto a WILDE, Store Kongensgade 18, c’è Buka Bakery se manca un caffè. Domenica Anonymous è chiuso: fate questo giro oggi.",
          hours: "WILDE sabato 11–17. Naked sabato 10–17. Anonymous sabato 10–17, chiuso domenica.",
          tickets: "Gratis entrare. Vintage WILDE è fascia alta.",
          how: "Da Købmagergade verso Kongens Nytorv, poi Store Kongensgade e le stradine a ovest.",
          duration: "1h 15min",
          lat: 55.6815,
          lng: 12.5838,
          maps: "WILDE, Store Kongensgade 22, Copenhagen",
        },
        {
          time: "16:00",
          title: "Collector’s Cage e Strøget",
          image: "img/stroget.jpg",
          place: "Collector’s Cage — Amagertorv 31",
          neighborhood: "Strøget",
          type: "shopping",
          description:
            "Borse vintage autenticate (Chanel, Bottega, Balenciaga) sulla piazza più centrale di Strøget. Poi vetrine verso Magasin e Kongens Nytorv. Se vi basta, fermatevi qui.",
          hours: "Sabato circa 11:00–18:00",
          tickets: "Gratis entrare",
          how: "Da Grønnegade, 6 minuti verso Amagertorv.",
          duration: "45 min",
          lat: 55.6789,
          lng: 12.5796,
          maps: "Collector's Cage, Amagertorv 31, Copenhagen",
        },
        {
          time: "16:50",
          title: "Christiansborg",
          image: "img/christiansborg.jpg",
          place: "Christiansborg Slot",
          neighborhood: "Slotsholmen",
          type: "visita",
          description:
            "Parlamento, sale reali e cortili sull’isola. Se arrivate prima delle 17:00 potete salire la torre (gratis, vista sulla città). Altrimenti gli esterni e il ponte verso il Diamante Nero bastano.",
          hours: "Sale e torre di solito 10:00–17:00. Cortili sempre percorribili",
          tickets: "Torre gratis. Sale reali a pagamento se volete l’interno.",
          how: "8 minuti da Amagertorv verso Højbro Plads e il palazzo.",
          duration: "30 min",
          lat: 55.6766,
          lng: 12.5806,
          maps: "Christiansborg Palace, Copenhagen",
        },
        {
          time: "17:25",
          title: "Biblioteca reale — Diamante Nero",
          image: "img/black-diamond.jpg",
          place: "Den Sorte Diamant — Det Kongelige Bibliotek",
          neighborhood: "Slotsholmen",
          type: "visita",
          description:
            "La biblioteca reale danese: il volume di vetro nero sull’acqua è lo stesso edificio. Sabato chiude alle 18:00: entrate, scendete al foyer sul porto, uscite dal lato Christianshavn. La vecchia università in Fiolstræde è un’altra cosa: quella è chiusa lunedì, la fate martedì.",
          hours: "Sabato di solito 9:00–18:00",
          tickets: "Foyer e lungomare gratis. Mostre a pagamento se ci sono.",
          how: "5 minuti a piedi da Christiansborg, lungo il canale verso sud.",
          duration: "35 min",
          lat: 55.6734,
          lng: 12.5824,
          maps: "The Black Diamond, Royal Danish Library, Copenhagen",
        },
        {
          time: "19:00",
          title: "Cena a Broens Street Food",
          image: "img/christianshavn.jpg",
          place: "Broens Gadekøkken — Strandgade 95",
          neighborhood: "Christianshavn",
          type: "cena",
          description:
            "Street food di sera, sul porto, accanto a Knippelsbro. Sabato i banchi stanno aperti fino alle 21:00, i bar più tardi. Prendete da un banco e una Fritz-Cola: è la cola che si beve qui (tedesca, ovunque a Copenaghen, non ha un locale suo). Barr è la porta accanto se volete tavolo, ma stasera è Broens.",
          hours: "Banchi ven–sab circa 11:00–21:00. Bar più tardi",
          tickets: "Piatto 90–160 DKK (~12–21 €). Fritz-Cola ~35 DKK (~5 €). Non si prenota il banco.",
          how: "Dal Diamante Nero, 8 minuti sul ponte verso Strandgade.",
          duration: "1h 30min",
          lat: 55.6751,
          lng: 12.5912,
          maps: "Broens Street Food, Strandgade 95, Copenhagen",
        },
      ],
    },
    {
      id: 3,
      date: "11 ottobre",
      year: "2026",
      weekday: "Domenica",
      shortDate: "11",
      title: "ARoS Aarhus: The Dome e ritorno per Delphine",
      neighborhoods: ["København H", "Aarhus", "Vesterbro"],
      summary:
        "Treno all’ARoS per The Dome di James Turrell e il Rainbow Panorama. Cena elegante da Delphine, a otto minuti dalla stazione centrale. Christiania slitta: il lunedì ARoS è chiuso.",
      image: "img/aros-rainbow.jpg",
      imageCredit: "Your rainbow panorama, ARoS",
      pace: "Gita in treno · ~3h per tratta",
      stops: [
        {
          time: "07:00",
          title: "Colazione da Buka e via alla stazione",
          image: "img/kongens-nytorv.jpg",
          place: "Buka Bakery — Store Kongensgade 18",
          neighborhood: "Indre By",
          type: "colazione",
          description:
            "Hart apre più tardi. Buka dalle 7:00, a 4 minuti dall’hotel: cardamomo da asporto e si parte. Se siete in ritardo, caffè e pane sul treno (DSB serve colazione fino alle 10:00).",
          hours: "Buka tutti i giorni circa 7:00–18:00",
          tickets: "50–90 DKK (~7–12 €) da asporto",
          how: "Da Borgergade verso Kongens Nytorv, Store Kongensgade 18.",
          duration: "15 min",
          lat: 55.6818,
          lng: 12.586,
          maps: "Buka Bakery, Store Kongensgade 18, Copenhagen",
        },
        {
          time: "07:25",
          title: "København H",
          image: "img/kbh-h.jpg",
          place: "Stazione centrale di Copenaghen",
          neighborhood: "Vesterbro",
          type: "trasporto",
          description:
            "Metro da Kongens Nytorv (una fermata, M3/M4) o 20 minuti a piedi. Controllate l’orario esatto su DSB / app: InterCityLyn per Aarhus, circa 2h 50min. Biglietto Orange se lo prendete in anticipo.",
          hours: "Treni frequentissimi tutta la mattina",
          tickets: "Andata e ritorno da circa 119–400 DKK (~16–53 €) a testa, secondo Orange o flessibile",
          how: "Metro Kongens Nytorv → København H, oppure a piedi per Strøget verso la stazione.",
          duration: "20 min",
          lat: 55.6728,
          lng: 12.5646,
          maps: "Copenhagen Central Station",
        },
        {
          time: "07:45",
          title: "Treno per Aarhus",
          image: "img/kbh-h.jpg",
          place: "DSB InterCityLyn · København H → Aarhus H",
          neighborhood: "In treno",
          type: "trasporto",
          description:
            "Senza cambi. Orario indicativo: partenza verso le 07:45, arrivo Aarhus H verso le 10:35. Verificate e prenotate su dsb.dk. Posto a sedere: vale la prenotazione, a ottobre è efterårsferie e i treni si riempiono.",
          hours: "Più di 30 partenze al giorno. ICL circa 2h 48min",
          tickets: "Stesso biglietto della tratta. Prenotate andata e ritorno.",
          how: "Binario in stazione: seguite Aarhus / ICL. Non è un treno regionale lento.",
          duration: "2h 50min",
          lat: 56.1504,
          lng: 10.2046,
          maps: "Aarhus H Station",
        },
        {
          time: "10:50",
          title: "ARoS: The Dome e Rainbow Panorama",
          image: "img/aros-rainbow.jpg",
          place: "ARoS Aarhus Kunstmuseum — Aros Allé 2",
          neighborhood: "Aarhus C",
          type: "visita",
          description:
            "Due cose, non una. Sotto terra: As Seen Below — The Dome, lo Skyspace di James Turrell (aperto da giugno 2026): si prenota lo slot su aros.dk. Sul tetto: Your rainbow panorama di Olafur Eliasson, l’anello di vetro colorato sulla città. Domenica 9:00–17:00. Il lunedì è chiuso, martedì volate: è oggi o niente.",
          hours: "Domenica 9:00–17:00. Da ottobre 2026 il lunedì è chiuso",
          tickets: "Adulto 200 DKK (~27 €). The Dome: prenotare la fascia oraria sul sito ARoS.",
          how: "10 minuti a piedi da Aarhus H, dritti verso Aros Allé 2.",
          duration: "2h 30min",
          lat: 56.1539,
          lng: 10.1997,
          maps: "ARoS Aarhus Art Museum",
        },
        {
          time: "13:30",
          title: "Pranzo all’ARoS Café",
          image: "img/aros.jpg",
          place: "ARoS Café & Orangery",
          neighborhood: "Aarhus C",
          type: "pranzo",
          description:
            "Caffè e Orangery del museo, ingresso libero anche senza biglietto. Pranzo leggero e si rientra in stazione. Non è Delphine: quella è la cena a Copenaghen.",
          hours: "Aperto negli orari del museo",
          tickets: "Pranzo 90–160 DKK (~12–21 €)",
          how: "Siete già dentro. Poi 10 minuti verso Aarhus H.",
          duration: "50 min",
          lat: 56.1539,
          lng: 10.1995,
          maps: "ARoS Café, Aarhus",
        },
        {
          time: "15:30",
          title: "Treno di rientro",
          image: "img/kbh-h.jpg",
          place: "DSB InterCityLyn · Aarhus H → København H",
          neighborhood: "In treno",
          type: "trasporto",
          description:
            "Partenza indicativa 15:30–16:00, arrivo København H verso le 18:30–19:00. Prendete quello che vi lascia in stazione almeno 45 minuti prima di Delphine. Non saltate l’ultimo ICL comodo.",
          hours: "ICL circa 2h 48min",
          tickets: "Ritorno già nel biglietto andata e ritorno",
          how: "Aarhus H, 10 minuti da ARoS.",
          duration: "2h 50min",
          lat: 55.6728,
          lng: 12.5646,
          maps: "Copenhagen Central Station",
        },
        {
          time: "19:30",
          title: "Cena da Delphine",
          image: "img/tivoli.jpg",
          place: "Delphine — Vesterbrogade 40",
          neighborhood: "Vesterbro",
          type: "cena",
          description:
            "La cena elegante: Mediterraneo, pesce e carne alla parrilla, sala alta e luminosa, a otto minuti a piedi da København H. Domenica aperti 17:30–00:00, ultimo arrivo 21:15. Prenotate su cofoco.dk: è il tavolo bello del viaggio, non è street food.",
          hours: "Dom–gio 17:30–00:00 (ultimo arrivo 21:15)",
          tickets: "Cena 400–700 DKK (~53–93 €). Prenotazione obbligatoria.",
          how: "Usciti da København H, Vesterbrogade verso ovest, numero 40. 8 minuti.",
          duration: "1h 45min",
          lat: 55.6726,
          lng: 12.5594,
          maps: "Delphine, Vesterbrogade 40, Copenhagen",
        },
      ],
    },
    {
      id: 4,
      date: "12 ottobre",
      year: "2026",
      weekday: "Lunedì",
      shortDate: "12",
      title: "Rosenborg, Torvehallerne e Tivoli Halloween",
      neighborhoods: ["Kongens Have", "Latinerkvarteret", "Nørrebro", "Tivoli"],
      summary:
        "Colazione da Andersen & Maillard, Rosenborg, Torvehallerne. Cena fissa da Poulette (il panino al pollo) e Tivoli di Halloween.",
      image: "img/rosenborg.jpg",
      imageCredit: "Rosenborg Slot",
      pace: "Giornata piena · castello + quartiere + sera",
      stops: [
        {
          time: "08:30",
          title: "Colazione da Andersen & Maillard",
          image: "img/lakes.jpg",
          place: "Andersen & Maillard — Nørrebrogade 62",
          neighborhood: "Nørrebro",
          type: "colazione",
          description:
            "Caffè tostato in casa e i croissant cubo più fotografati della città. È 20 minuti dall’hotel, sulla strada dei laghi: fate colazione qui e rientrate verso Rosenborg a piedi lungo Søerne. Stessa palazzina di Poulette, dove cenate stasera.",
          hours: "Di solito dalla mattina a metà pomeriggio; coda nel weekend, lunedì è più civile",
          tickets: "Caffè e pastry 60–120 DKK (~8–16 €)",
          how: "Da Borgergade verso i laghi, poi Nørrebrogade. 20 minuti a piedi.",
          duration: "40 min",
          lat: 55.6888,
          lng: 12.5562,
          maps: "Andersen & Maillard, Nørrebrogade 62, Copenhagen",
        },
        {
          time: "10:00",
          title: "Rosenborg e Kongens Have",
          image: "img/rosenborg.jpg",
          place: "Rosenborg Slot e Kongens Have",
          neighborhood: "Kongens Have",
          type: "visita",
          description:
            "Il giardino del re è il parco sotto casa: siepi, statue, prato. Poi il castello olandese e i gioielli della corona. Se dovete scegliere un solo palazzo a pagamento, è questo.",
          hours: "10:00–17:00 tutti i giorni in ottobre",
          tickets: "140 DKK (~19 €) online / 150 DKK (~20 €) in cassa",
          how: "Dai laghi verso Øster Voldgade 4A, ingresso dal parco.",
          duration: "1h 15min",
          lat: 55.6867,
          lng: 12.5774,
          maps: "Rosenborg Castle, Copenhagen",
        },
        {
          time: "11:20",
          title: "Orto Botanico",
          image: "img/botanical.jpg",
          place: "Botanisk Have — Gothersgade 128",
          neighborhood: "Nørreport",
          type: "passeggiata",
          description:
            "Attaccato a Kongens Have. Serre palma, laghetto, quiete. In ottobre è aperto fino alle 18:00. Dieci minuti lenti, poi si scende in Krystalgade.",
          hours: "Fino al 24 ottobre circa 8:30–18:00",
          tickets: "Giardino gratis. Palmehus a pagamento se volete le serre.",
          how: "Uscita ovest di Kongens Have, attraversate Gothersgade.",
          duration: "25 min",
          lat: 55.6871,
          lng: 12.5746,
          maps: "Botanical Garden, Gothersgade 128, Copenhagen",
        },
        {
          time: "11:50",
          title: "Biblioteca pubblica — Hovedbiblioteket",
          image: "img/library.jpg",
          place: "Københavns Hovedbibliotek",
          neighborhood: "Latinerkvarteret",
          type: "visita",
          description:
            "La biblioteca centrale in Krystalgade 15, quattro piani, giornali, silenzio, e il bar Democratic Coffee al piano terra. È a due minuti dalla Torre Rotonda: entrate, salite, capite come i danesi usano lo spazio pubblico. Gratis.",
          hours: "Lunedì spesso 8:00–22:00 (orari estesi / self service). Banco circa 10:00–19:00",
          tickets: "Gratis. Democratic Coffee a parte se volete un caffè, non è un pasto.",
          how: "Dall’Orto Botanico 8 minuti verso Krystalgade.",
          duration: "30 min",
          lat: 55.681,
          lng: 12.5753,
          maps: "Københavns Hovedbibliotek, Krystalgade 15, Copenhagen",
        },
        {
          time: "12:25",
          title: "Rundetårn",
          image: "img/rundetaarn.jpg",
          place: "Rundetårn",
          neighborhood: "Latinerkvarteret",
          type: "visita",
          description:
            "Rampa elicoidale, niente scale, tetti da vicino. Lunedì aperta fino alle 21:00. L’osservatorio nel 2026 è in restauro: si sale comunque.",
          hours: "Lunedì e martedì 10:00–21:00",
          tickets: "60 DKK (~8 €). Solo in cassa, non è nel Copenhagen Card.",
          how: "Købmagergade 52A, 2 minuti dalla biblioteca.",
          duration: "35 min",
          lat: 55.6814,
          lng: 12.5758,
          maps: "Round Tower, Copenhagen",
        },
        {
          time: "13:10",
          title: "Shopping: Samsøe Samsøe e Carmen",
          image: "img/vor-frue.jpg",
          place: "Købmagergade e Larsbjørnsstræde",
          neighborhood: "Latinerkvarteret",
          type: "shopping",
          description:
            "Samsøe Samsøe flagship in Købmagergade 48, attaccata alla torre: maglieria danese, la più utile da portare a casa. Carmen Copenhagen in Larsbjørnsstræde 5 (Pisserenden, 6 minuti): vintage vecchia scuola, vestiti, occhiali, pellicce. Lunedì entrambe aperte. WILDE oggi è chiuso, l’avete fatto sabato.",
          hours: "Samsøe di solito 10:00–18:00. Carmen lun–gio circa 11:00–18:00",
          tickets: "Gratis entrare",
          how: "Samsøe è sotto la torre. Carmen: Nørregade → Larsbjørnsstræde.",
          duration: "50 min",
          lat: 55.6811,
          lng: 12.576,
          maps: "Samsøe Samsøe, Købmagergade 48, Copenhagen",
        },
        {
          time: "14:10",
          title: "Pranzo a Torvehallerne",
          image: "img/torvehallerne.jpg",
          place: "Torvehallerne — Frederiksborggade 21",
          neighborhood: "Nørreport",
          type: "pranzo",
          description:
            "Il food market coperto accanto a Nørreport: due padiglioni, banconi, pesce, smørrebrød, caffè. Gasoline è già stata sabato, oggi è questo. Un banco, si mangia in piedi. Lunedì chiude alle 19:00.",
          hours: "Lun–ven circa 10:00–19:00",
          tickets: "Pranzo 80–160 DKK (~11–21 €). Si paga al banco.",
          how: "5 minuti da Samsøe verso Nørreport / Frederiksborggade.",
          duration: "50 min",
          lat: 55.6838,
          lng: 12.5701,
          maps: "Torvehallerne, Frederiksborggade 21, Copenhagen",
        },
        {
          time: "15:30",
          title: "Nørrebro: laghi, Assistens, Jægersborggade",
          image: "img/assistens.jpg",
          place: "Assistens Kirkegård e Jægersborggade",
          neighborhood: "Nørrebro",
          type: "passeggiata",
          description:
            "Ritorno a Nørrebro senza fretta. Cimitero-parco (Andersen, Kierkegaard), poi Jægersborggade. Verso le 17:15 siete di nuovo su Nørrebrogade 62.",
          hours: "Cimitero di solito 7:00–19:00 in ottobre",
          tickets: "Gratis",
          how: "A piedi lungo i laghi (20 min da Købmagergade) o bus verso Nørrebrogade.",
          duration: "1h 15min",
          lat: 55.6908,
          lng: 12.5506,
          maps: "Assistens Kirkegård, Copenhagen",
        },
        {
          time: "17:15",
          title: "Cena da Poulette — il panino al pollo",
          image: "img/lakes.jpg",
          place: "Poulette — Nørrebrogade 62",
          neighborhood: "Nørrebro",
          type: "cena",
          description:
            "Tappa fissa, come Gasoline per il burger: qui è il panino al pollo. Croccante, stesso isolato di Andersen & Maillard. Non lo saltate per Tivoli: mangiate qui, poi entrate al parco.",
          hours: "Verificare; di solito pranzo e prima serata",
          tickets: "Piatto 100–180 DKK (~13–24 €). Spesso senza prenotazione.",
          how: "Nørrebrogade 62, stesso isolato di Andersen & Maillard.",
          duration: "45 min",
          lat: 55.6888,
          lng: 12.5562,
          maps: "Poulette, Nørrebrogade 62, Copenhagen",
        },
        {
          time: "18:15",
          title: "Tivoli Halloween",
          image: "img/tivoli.jpg",
          place: "Tivoli Gardens",
          neighborhood: "Vesterbro / Rådhuspladsen",
          type: "visita",
          description:
            "Visita di Halloween: zucche, luci, tramonto verso le 18:20. Il 12 ottobre è vacanza scolastica, sarà pieno. L’ingresso non include le giostre. Non saltatela: è la sera del parco.",
          hours: "Halloween 2026: da circa 11:00 a 22:00",
          tickets: "Ingresso da circa 150 DKK (~20 €). Ride Pass extra da ~299 DKK (~40 €). Meglio online.",
          how: "Da Nørrebro, metro o 25 minuti a piedi fino a Vesterbrogade 3.",
          duration: "2h–2h 30min",
          lat: 55.6737,
          lng: 12.5681,
          maps: "Tivoli Gardens, Copenhagen",
        },
      ],
    },
    {
      id: 5,
      date: "13 ottobre",
      year: "2026",
      weekday: "Martedì",
      shortDate: "13",
      title: "Biblioteca, Glyptoteket, Kaktus e volo",
      neighborhoods: ["Indre By", "Vesterbro", "Bispebjerg", "Aeroporto"],
      summary:
        "Buka a colazione, vecchia biblioteca universitaria (oggi è aperta), Glyptoteket, Kaktus Towers, pranzo da Jagger. Se resta tempo, Grundtvigs Kirke. Metro alle 17:30.",
      image: "img/glyptotek.jpg",
      imageCredit: "Glyptoteket",
      pace: "Mattina piena · partenza",
      stops: [
        {
          time: "08:15",
          title: "Colazione da Buka Bakery",
          image: "img/kongens-nytorv.jpg",
          place: "Buka Bakery — Store Kongensgade 18",
          neighborhood: "Indre By",
          type: "colazione",
          description:
            "Il forno a 4 minuti dall’hotel, accanto a WILDE. Cardamomo, focaccia, caffè. Aperto tutti i giorni dalle 7:00. Oggi Hart la lasciate: è il giorno di Buka.",
          hours: "Tutti i giorni circa 7:00–18:00",
          tickets: "60–110 DKK (~8–15 €). Da asporto o pochi posti.",
          how: "Da Borgergade verso Kongens Nytorv, Store Kongensgade 18 a destra.",
          duration: "30 min",
          lat: 55.6818,
          lng: 12.586,
          maps: "Buka Bakery, Store Kongensgade 18, Copenhagen",
        },
        {
          time: "10:00",
          title: "Vecchia biblioteca universitaria",
          image: "img/library.jpg",
          place: "Universitetsbiblioteket — Fiolstræde 1",
          neighborhood: "Latinerkvarteret",
          type: "visita",
          description:
            "La sala di lettura ottocentesca, legno e gallerie. Aperta solo mar–sab 10:00–17:00: lunedì e domenica è chiusa, quindi oggi o niente. 75 DKK (~10 €), un giro di 40 minuti. Non è il Diamante Nero: quella l’avete vista sabato.",
          hours: "Mar–sab 10:00–17:00. Chiusa lunedì e domenica",
          tickets: "75 DKK (~10 €)",
          how: "15 minuti dall’hotel verso Fiolstræde, dietro Vor Frue Kirke.",
          duration: "40 min",
          lat: 55.6807,
          lng: 12.5728,
          maps: "The Old University Library, Fiolstræde 1, Copenhagen",
        },
        {
          time: "10:50",
          title: "Ny Carlsberg Glyptotek",
          image: "img/glyptotek.jpg",
          place: "Glyptoteket",
          neighborhood: "Vesterbro",
          type: "visita",
          description:
            "Sculture, impressionisti, giardino d’inverno sotto vetro. Martedì è aperto. Non allungate troppo: dopo c’è Kaktus e Jagger.",
          hours: "Di solito 10:00–17:00, chiuso il lunedì",
          tickets: "135 DKK (~18 €) online / 150 DKK (~20 €) in cassa",
          how: "12 minuti a piedi da Fiolstræde verso Dantes Plads 7.",
          duration: "1h 10min",
          lat: 55.6726,
          lng: 12.5724,
          maps: "Glyptoteket, Copenhagen",
        },
        {
          time: "12:10",
          title: "Kaktus Towers",
          image: "img/kaktus.jpg",
          place: "Kaktustårnene — Dybbølsbro",
          neighborhood: "Vesterbro",
          type: "passeggiata",
          description:
            "Le due torri a cactus di BIG, sopra la stazione Dybbølsbro, verso Fisketorvet. Si guarda da fuori, non si entra. Dieci minuti di foto e via verso Jagger.",
          hours: "Esterni sempre visibili",
          tickets: "Gratis",
          how: "15 minuti a piedi dal Glyptoteket verso sud, stazione Dybbølsbro.",
          duration: "20 min",
          lat: 55.6637,
          lng: 12.5612,
          maps: "Kaktus Towers, Dybbølsbro, Copenhagen",
        },
        {
          time: "12:45",
          title: "Pranzo da Jagger",
          image: "img/city-hall.jpg",
          place: "Jagger — H.C. Andersens Boulevard 12",
          neighborhood: "Rådhuspladsen",
          type: "pranzo",
          description:
            "Smash burger danese in piazza del Municipio, sulla via del rientro. Non sostituisce Gasoline: quello l’avete già fatto sabato. C’è anche Jagger in Købmagergade 43, se preferite il centro.",
          hours: "Pranzo e cena, tutti i giorni",
          tickets: "Burger 90–140 DKK (~12–19 €). Non si prenota.",
          how: "10 minuti da Dybbølsbro verso Rådhuspladsen.",
          duration: "40 min",
          lat: 55.6756,
          lng: 12.5687,
          maps: "Jagger, H.C. Andersens Boulevard 12, Copenhagen",
        },
        {
          time: "13:40",
          title: "Grundtvigs Kirke",
          image: "img/grundtvig.jpg",
          place: "Grundtvigs Kirke — På Bjerget 14B",
          neighborhood: "Bispebjerg",
          type: "visita",
          description:
            "Cattedrale espressionista di mattoni gialli, a nord. Martedì è aperta circa 10:00–15:45; lunedì è chiusa. Metro/S-tog verso Bispebjerg, 25 minuti. Se il tempo è corto, saltate l’interno e fate solo la facciata: vale comunque. Siate in hotel verso le 16:00.",
          hours: "Martedì di solito 10:00–15:45. Lunedì chiusa. Verificare il sito il giorno stesso",
          tickets: "Chiesa gratis. Torre solo con visita guidata.",
          how: "Da Rådhuspladsen: S-tog o metro verso Nørrebro/Bispebjerg, poi 10 minuti a piedi. Indirizzo På Bjerget 14B.",
          duration: "1h 15min andata e ritorno",
          lat: 55.7167,
          lng: 12.5336,
          maps: "Grundtvigs Kirke, På Bjerget 14B, Copenhagen",
        },
        {
          time: "16:00",
          title: "Pausa in hotel e valigie",
          image: "img/kongens-nytorv.jpg",
          place: "Wakeup Borgergade",
          neighborhood: "Indre By",
          type: "hotel",
          description:
            "Check-out spesso alle 11:00: lasciate i bagagli in deposito al mattino. Doccia, ricarica, niente corsa.",
          hours: "Deposito bagagli in reception",
          tickets: "—",
          how: "Siete in zona.",
          duration: "flessibile",
          lat: 55.6835,
          lng: 12.5867,
          maps: "Wakeup Copenhagen Borgergade, Borgergade 9",
        },
        {
          time: "17:30",
          title: "Metro verso CPH",
          image: "img/metro.jpg",
          place: "Kongens Nytorv → Lufthavnen",
          neighborhood: "Aeroporto",
          type: "trasporto",
          description:
            "M2 direzione Lufthavnen, 14 minuti. Per easyJet delle 20:30 in aeroporto alle 18:00 è comodo.",
          hours: "Metro 24/7",
          tickets: "30 DKK a persona (~4 €), 3 zone",
          how: "5 minuti a piedi dall’hotel alla metro.",
          duration: "25 min",
          lat: 55.6798,
          lng: 12.5856,
          maps: "Kongens Nytorv Station, Copenhagen",
        },
        {
          time: "20:30",
          title: "Volo per Milano Linate",
          image: "img/cph-airport.jpg",
          place: "Copenhagen Airport",
          neighborhood: "Kastrup",
          type: "volo",
          description:
            "easyJet CPH → LIN, arrivo a Linate alle 22:35.",
          hours: "Imbarco secondo easyJet",
          tickets: "Volo già prenotato",
          how: "La metro arriva sotto il Terminal 3.",
          duration: "2h 05min",
          lat: 55.618,
          lng: 12.6508,
          maps: "Copenhagen Airport CPH",
        },
      ],
    },
  ],
};
